name: salat_tracker
description: "Salat Tracker prayer log."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.7

dependencies:
  animations: ^2.1.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  flutter_svg: ^2.2.3
  flutter_timezone: ^5.0.1
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  hive_ce: ^2.18.0
  hive_ce_flutter: ^2.3.4
  intl: ^0.20.2
  json_annotation: ^4.9.0
  locale_names: ^1.1.1
  permission_handler: ^12.0.1
  riverpod_annotation: ^4.0.0
  sentry_flutter: ^9.10.0
  table_calendar: ^3.2.0
  timezone: ^0.10.1

dev_dependencies:
  build_runner: ^2.10.5
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  hive_ce_generator: ^1.10.0
  intl_utils: ^2.8.13
  json_serializable: ^6.11.2
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  main_locale: ar
  arb_dir: lib/core/localization/gen/l10n
  output_dir: lib/core/localization/gen/generated
